version : 0.0
os : linux

hooks:
  ApplicationStop:
    - location: stopstartscript/stopcontainer.sh
      timeout: 30
      runas: root
  Afterinstall:
    - location: stopstartscript/startcontainer.sh
      timeout: 30
      runas: root
